name: dalla
description: "A ride hailing app"
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.4.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  #firebase_core: ^2.20.0
  #firebase_auth: ^6.11.0
  #cloud_firestore: ^4.12.1
  #provider: any
  #google_maps_flutter: ^3.20.1

  cupertino_icons: ^1.0.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
